### ISSUE TITLE
[VencordRPC] Plugin doesn't work

### ISSUE THREAD

**Issue by RobinRMC** [AutumnVN/userplugins#1]
The plugin just doesn't work.

I've installed it correctly and it enables when loading Vencord, but doesn't show any rich presence. However, it does block the rich presence from CustomRPC.

**Comment by AutumnVN** [comment]
works on my machine
![image](https://github.com/AutumnVN/userplugins/assets/77253698/bcc1afab-da54-4be3-b6f9-7d834ba37a58)

**Comment by RobinRMC** [comment]
I'm using Vesktop. Could that be the issue?

**Comment by AutumnVN** [comment]
that screenshot was on vesktop too

**Comment by AutumnVN** [comment]
it does same as customRPC, just the content dynamically changing base on what channel you are looking at
