### ISSUE TITLE
screen record plugin doesn't show in plugins and did pnpm build and all other plugins are showing

### ISSUE THREAD

**Issue by Cxsmo-ai** [AutumnVN/userplugins#2]
screen record plugin doesn't show in plugins and did pnpm build and all other plugins are showing

**Comment by AutumnVN** [comment]
use vesktop

**Comment by Cxsmo-ai** [comment]
why vesktop only

**Comment by AutumnVN** [comment]
discord app doesnt support mediaDevices.getDisplayMedia
